language: android
android:
 components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository

jdk: oraclejdk8

script:
  - mvn android:lint
  - mvn test
after_failure: cat target/lint-results/lint-results.xml || true
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
